version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./initMysql.sql:/docker-entrypoint-initdb.d/initMysql.sql
    command: --default-authentication-plugin=mysql_native_password
volumes:
  mysql_data:
